<div style="text-align: center"> <h1>Exp.2. Perform Mathematical Computing using NumPy - Array and Matrices</h1></div>


**Aim:**
To perform mathematical operations using NumPy python library and understand the data handling features of the library.

**Procedure:**

Step 1: Start the ‘ipython’ session from the terminal

Step 2: Check the Numpy version installed in your environment by typing ‘numpy.__version__’

Step 3: If not installed means run the ‘%pip install numpy’ magic command to install the library

Step 4: Import the library in the session with an alias by typing ‘import numpy as np’

Step 5: Perform matrix operations such as inner product, dot product, Transpose, Rank, Determinant, True Inverse, Eigenvalues and Eigenvectors

Step 6: Verify the output

# Program: 
### Numpy Inner Product ###

In [1]:
import numpy as np
# Vectors as 1D numpy arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("a= ", a)
print("b= ", b)
print("\inner:", np.inner(a, b))

a=  [1 2 3]
b=  [4 5 6]
\inner: 32


### Numpy Dot Product of Matrices ###

In [2]:
# Matrices as matrix objects
c = np.matrix([[1, 2], [3, 4]])
d = np.matrix([[5, 6, 7], [8, 9, 10]])
print("\nc", type(c))
print(c)
print("\nd", type(d))
print(d)
print("\ndot product of two matrix objects")
print(np.dot(c, d))


c <class 'numpy.matrix'>
[[1 2]
 [3 4]]

d <class 'numpy.matrix'>
[[ 5  6  7]
 [ 8  9 10]]

dot product of two matrix objects
[[21 24 27]
 [47 54 61]]


### Transpose of a Matrix ###

In [3]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print("a = ")
print(a)
print("\nWith np.transpose(a) function")
print(np.transpose(a))
print("\nWith ndarray.transpose() method")
print(a.transpose())
print("\nWith ndarray.T short form")
print(a.T)

a = 
[[1 2]
 [3 4]
 [5 6]]

With np.transpose(a) function
[[1 3 5]
 [2 4 6]]

With ndarray.transpose() method
[[1 3 5]
 [2 4 6]]

With ndarray.T short form
[[1 3 5]
 [2 4 6]]


### Rank of matrix ###

In [4]:
a = np.arange(1, 10)
a.shape = (3, 3)
print("a = ")
print(a)
rank = np.linalg.matrix_rank(a)
print("\nRank:", rank)

a = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Rank: 2


### Determinant of a Matrix ###

In [5]:
a = np.array([[2, 2, 1],
 [1, 3, 1],
[1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))


a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0


### True Inverse of a matrix ###

In [6]:
a = np.array([[2, 2, 1],
 [1, 3, 1],
 [1, 2, 2]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))
inv = np.linalg.inv(a)
print("\nInverse of a = ")
print(inv)

a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Determinant: 5.0

Inverse of a = 
[[ 0.8 -0.4 -0.2]
 [-0.2  0.6 -0.2]
 [-0.2 -0.4  0.8]]


### Eigenvalues and Eigenvectors of a matrix ###

In [7]:
a = np.array([[2, 2, 1],
 [1, 3, 1],
 [1, 2, 2]])
print("a = ")
print(a)
w, v = np.linalg.eig(a)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)


a = 
[[2 2 1]
 [1 3 1]
 [1 2 2]]

Eigenvalues:
[5. 1. 1.]

Eigenvectors:
[[ 0.57735027  0.90453403  0.36601928]
 [ 0.57735027 -0.30151134 -0.55609927]
 [ 0.57735027 -0.30151134  0.74617926]]


**Result:**

Thus, the features of the Numpy library are studied and it’s uses in mathematical computation is demonstrated successfully.
